### ISSUE TITLE
🚧Add/update issue and PR templates

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/ReleaseAnnouncer#4]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update issue and PR templates to match that of Velaptor

### Acceptance Criteria

**This issue is finished when:**
- Issue templates updated
  - [ ] bug-issue-template.yml updated
  - [ ] feature-request-issue-template.yml updated
  - [ ] release-todo-issue-template.yml updated
  - [ ] project-item-issue-template.yml updated
  - [ ] qa-testing-template.yml updated
  - [ ] research-issue-template.yml updated
- PR templates updated and text `-template` added to the end of the file before the file extension
  - [ ] feature-pr.md
  - [ ] preview-feature-pr.md
  - [ ] preview-release-pr.md
  - [ ] production-release-pr.md
- [ ] Add/update config.yml

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
Decided that this will be created from a template repo.  Nothing added/modified.  Issue closed.
